stages:
  split:
    cmd: python src/data/split.py
    deps:
      - src/data/split.py
      - data/raw_data/raw.csv
    outs:
      - data/processed_data/X_train.csv
      - data/processed_data/X_test.csv
      - data/processed_data/y_train.csv
      - data/processed_data/y_test.csv

  normalize:
    cmd: python src/data/normalization.py
    deps:
      - src/data/normalization.py
      - data/processed_data/X_train.csv
      - data/processed_data/X_test.csv
    outs:
      - data/processed_data/X_train_scaled.csv
      - data/processed_data/X_test_scaled.csv

  gridsearch:
    cmd: python src/models/gridsearch.py
    deps:
      - src/models/gridsearch.py
      - data/processed_data/X_train_scaled.csv
      - data/processed_data/y_train.csv
    outs:
      - models/best_params.pkl

  training:
    cmd: python src/models/train.py
    deps:
      - src/models/train.py
      - data/processed_data/X_train_scaled.csv
      - data/processed_data/y_train.csv
      - models/best_params.pkl
    outs:
      - models/gbr_model.pkl

  evaluate:
    cmd: python src/models/evaluate.py
    deps:
      - src/models/evaluate.py
      - models/gbr_model.pkl
      - data/processed_data/X_test_scaled.csv
      - data/processed_data/y_test.csv
    outs:
      - data/processed_data/prediction.csv
    metrics:
      - metrics/scores.json
